### ISSUE TITLE
Issue with assimp 5.2.4 (5.2.4-h4dcb625_1) on Windows

### ISSUE THREAD

**Issue by jcarpent** [conda-forge/assimp-feedstock#45]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

During the update of hpp-fcl for boost 1.78 (https://github.com/conda-forge/hpp-fcl-feedstock/pull/69), it seems that a new issue appears with the recent update of the assimp package with boost 1.78 for windows, and related to this merged PR (https://github.com/conda-forge/assimp-feedstock/pull/44).
Please see the build status of hpp-fcl https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=566666&view=results

Yesterday, everything was working on hpp-fcl as highlighted by this merged PR (https://github.com/conda-forge/hpp-fcl-feedstock/pull/68).

@wolfv @xhochy @traversaro Do you know where does the issue come from?

### Installed packages

```shell
None
```

### Environment info

```shell
Windows env
```

**Comment by traversaro** [comment]
I am not sure what is happening and how this changed with the new assimp build, but from the failing job the error from: 
~~~
2022-09-11T13:36:26.8069273Z 	%BUILD_PREFIX%\Library\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\hpp-fcl.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\hpp-fcl.dir\objects1.rsp @C:\Users\VSSADM~1\AppData\Local\Temp\nm48CE.tmp
2022-09-11T13:36:27.2573473Z LINK: command "C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\hpp-fcl.dir\objects1.rsp /out:hpp-fcl.dll /implib:hpp-fcl.lib /pdb:%SRC_DIR%\build\src\hpp-fcl.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO %PREFIX%\Library\lib\boost_serialization.lib %PREFIX%\Library\lib\boost_chrono.lib %PREFIX%\Library\lib\octomap.lib %PREFIX%\Library\lib\octomath.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:hpp-fcl.dll.manifest" failed (exit code 1) with the following output:
~~~
is that that the assimp-v142-mt.lib is not properly linked.

**Comment by traversaro** [comment]
I think I got what is happening. https://github.com/conda-forge/assimp-feedstock/pull/44 also rerendered the feedstock, that bumped the version of VS used to compiled the library from VS2017 and VS2019. 

In most cases this is an harmless and ABI-compatible change (at least if the library is then consumed by VS2019 library and executables), but in the case of assimp this induced an undected ABI break, as the name of the library changed from `assimp-vc141-mt.(lib|dll)` to `assimp-vc142-mt.(lib|dll)`. So, this is a first problem, but it is not the problem in your case, as in that case a new library is compiled so a change in assimp name would not be a problem. I think that in hpp-fcl case, I think that the problem is the `Findassimp.cmake` file used, that if I am not wrong is silently ignoring assimp libraries named `assimp-vc142-mt.(lib|dll)`, see the code around https://github.com/humanoid-path-planner/hpp-fcl/blob/v2.1.2/cmake-modules/Findassimp.cmake#L22 .

**Comment by jcarpent** [comment]
@traversaro Thanks for the quick reply. Very nice catch ;)

**Comment by traversaro** [comment]
To be more robust again change of library name, it is a good idea to use `find_package(assimp CONFIG)` inside your `FindAssimp.cmake`. Unfortunatly the problem is that historically that the assimp cmake config file packaged in Debian/Ubuntu distribution had several bugs. In iDynTree I have some workarounds for this in https://github.com/robotology/idyntree/blob/fb0b5d311775149afce1e97562c0b418d04a70d5/cmake/iDynTreeDependencies.cmake#L98, a possible strategy is to take that workarounds, and pack them in a `Findassimp.cmake` after a `find_package(assimp CONFIG REQUIRED)` or similar.

**Comment by traversaro** [comment]
I think this was fixed by:
* https://github.com/conda-forge/admin-requests/pull/484
* https://github.com/conda-forge/assimp-feedstock/pull/47
* https://github.com/conda-forge/assimp-feedstock/pull/48

Do you agree on closing @jcarpent ?

**Comment by jcarpent** [comment]
Yes, sure. Thanks @traversaro.
